/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventMessageType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8407537266843772281L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventMessageType\",\"namespace\":\"com.example.domain\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"]},{\"name\":\"event_history\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"event_history_record\",\"fields\":[{\"name\":\"event_processor\",\"type\":\"string\"},{\"name\":\"time_received\",\"type\":\"string\"},{\"name\":\"time_published\",\"type\":\"string\"},{\"name\":\"topic_published\",\"type\":\"string\"},{\"name\":\"error_code\",\"type\":\"int\"},{\"name\":\"error_message\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventMessageType> ENCODER =
      new BinaryMessageEncoder<EventMessageType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventMessageType> DECODER =
      new BinaryMessageDecoder<EventMessageType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventMessageType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventMessageType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventMessageType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventMessageType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventMessageType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventMessageType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventMessageType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventMessageType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.CharSequence description;
   private java.util.List<com.example.domain.event_history_record> event_history;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventMessageType() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param description The new value for description
   * @param event_history The new value for event_history
   */
  public EventMessageType(java.lang.Long id, java.lang.CharSequence description, java.util.List<com.example.domain.event_history_record> event_history) {
    this.id = id;
    this.description = description;
    this.event_history = event_history;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return description;
    case 2: return event_history;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    case 2: event_history = (java.util.List<com.example.domain.event_history_record>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'event_history' field.
   * @return The value of the 'event_history' field.
   */
  public java.util.List<com.example.domain.event_history_record> getEventHistory() {
    return event_history;
  }


  /**
   * Sets the value of the 'event_history' field.
   * @param value the value to set.
   */
  public void setEventHistory(java.util.List<com.example.domain.event_history_record> value) {
    this.event_history = value;
  }

  /**
   * Creates a new EventMessageType RecordBuilder.
   * @return A new EventMessageType RecordBuilder
   */
  public static com.example.domain.EventMessageType.Builder newBuilder() {
    return new com.example.domain.EventMessageType.Builder();
  }

  /**
   * Creates a new EventMessageType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventMessageType RecordBuilder
   */
  public static com.example.domain.EventMessageType.Builder newBuilder(com.example.domain.EventMessageType.Builder other) {
    if (other == null) {
      return new com.example.domain.EventMessageType.Builder();
    } else {
      return new com.example.domain.EventMessageType.Builder(other);
    }
  }

  /**
   * Creates a new EventMessageType RecordBuilder by copying an existing EventMessageType instance.
   * @param other The existing instance to copy.
   * @return A new EventMessageType RecordBuilder
   */
  public static com.example.domain.EventMessageType.Builder newBuilder(com.example.domain.EventMessageType other) {
    if (other == null) {
      return new com.example.domain.EventMessageType.Builder();
    } else {
      return new com.example.domain.EventMessageType.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventMessageType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventMessageType>
    implements org.apache.avro.data.RecordBuilder<EventMessageType> {

    private long id;
    private java.lang.CharSequence description;
    private java.util.List<com.example.domain.event_history_record> event_history;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.domain.EventMessageType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.event_history)) {
        this.event_history = data().deepCopy(fields()[2].schema(), other.event_history);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing EventMessageType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.domain.EventMessageType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.event_history)) {
        this.event_history = data().deepCopy(fields()[2].schema(), other.event_history);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'event_history' field.
      * @return The value.
      */
    public java.util.List<com.example.domain.event_history_record> getEventHistory() {
      return event_history;
    }


    /**
      * Sets the value of the 'event_history' field.
      * @param value The value of 'event_history'.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder setEventHistory(java.util.List<com.example.domain.event_history_record> value) {
      validate(fields()[2], value);
      this.event_history = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'event_history' field has been set.
      * @return True if the 'event_history' field has been set, false otherwise.
      */
    public boolean hasEventHistory() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'event_history' field.
      * @return This builder.
      */
    public com.example.domain.EventMessageType.Builder clearEventHistory() {
      event_history = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventMessageType build() {
      try {
        EventMessageType record = new EventMessageType();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.event_history = fieldSetFlags()[2] ? this.event_history : (java.util.List<com.example.domain.event_history_record>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventMessageType>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventMessageType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventMessageType>
    READER$ = (org.apache.avro.io.DatumReader<EventMessageType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    if (this.description == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.description);
    }

    long size0 = this.event_history.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.example.domain.event_history_record e0: this.event_history) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      if (in.readIndex() != 0) {
        in.readNull();
        this.description = null;
      } else {
        this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
      }

      long size0 = in.readArrayStart();
      java.util.List<com.example.domain.event_history_record> a0 = this.event_history;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.example.domain.event_history_record>((int)size0, SCHEMA$.getField("event_history").schema());
        this.event_history = a0;
      } else a0.clear();
      SpecificData.Array<com.example.domain.event_history_record> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.domain.event_history_record>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.example.domain.event_history_record e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.example.domain.event_history_record();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.description = null;
          } else {
            this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          }
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<com.example.domain.event_history_record> a0 = this.event_history;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.example.domain.event_history_record>((int)size0, SCHEMA$.getField("event_history").schema());
            this.event_history = a0;
          } else a0.clear();
          SpecificData.Array<com.example.domain.event_history_record> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.domain.event_history_record>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.example.domain.event_history_record e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.example.domain.event_history_record();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










